Repository uc-cdis/gitops-qa-v2, pull requests merged in 2020-07, with the labels that each got.

#1 chore(qa): 1st Pr check run in qaplanetv2
  Jenkinsfile
  ci-env-1.planx-pla.net/manifest.json
Labels: qaplanetv2, test-portal-homepageTest

#7 chore(qa): Update sower jobs for ci-env-1
  ci-env-1.planx-pla.net/manifest.json
Labels: automerge, qaplanetv2, test-portal-homepageTest

#5 Updating CI env with integration202008 ci-env-1.planx-pla.net 1594845870
  ci-env-1.planx-pla.net/manifest.json
  ci-env-1.planx-pla.net/manifests/hatchery/hatchery.json
Labels: qaplanetv2, test-portal-indexingPageTest, test-sheepdogAndPeregrine-submitAndQueryNodesTest
